### 로그인

POST {{host}}/v1/members/sign-in
Content-Type: application/json

{
  "name": "jh"
}

### 프로필 조회

GET {{host}}/v1/members/profile
Content-Type: application/json
Authorization: Bearer {{token}}

### 회차 완료

POST {{host}}/v1/members/progress/complete
Content-Type: application/json
Authorization: Bearer {{token}}
