### 단어 텍스트로 추가

POST {{host}}/v1/words/texts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "words": [
    {
      "name": "A",
      "meaning": "A"
    },
    {
      "name": "B",
      "meaning": "B"
    },
    {
      "name": "C",
      "meaning": "C"
    }
  ]
}

### 단어 랜덤 출제

GET {{host}}/v1/words/status/not-solved/random
Authorization: Bearer {{token}}

### 미제출 단어 존재 여부

GET {{host}}/v1/words/status/not-solved/existence
Authorization: Bearer {{token}}

### 등록한 단어중 미출제 단어들 조회

GET {{host}}/v1/words/status/not-solved
Authorization: Bearer {{token}}

### 해당 주차 단어들 조회

GET {{host}}/v1/words/weeks/5
Authorization: Bearer {{token}}

### 해당 주차에 등록된 단어들 개수 조회

GET {{host}}/v1/words/weeks/5/count
Authorization: Bearer {{token}}