### 단어 텍스트로 추가

POST localhost:8080/v1/words/texts
Content-Type: application/json

{
  "words": [
    {
      "name": "A",
      "meaning": "A"
    },
    {
      "name": "B",
      "meaning": "B"
    },
    {
      "name": "C",
      "meaning": "C"
    }
  ]
}

### 단어 랜덤 제출

GET 3.39.240.48:8080/v1/words/status/not-solved/random

### 미제출 단어 존재 여부

GET 3.39.240.48:8080/v1/words/status/not-solved/existence